version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Exposes Grafana on http://localhost:3000
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    extra_hosts:
      - "host.docker.internal:host-gateway"

