apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    isDefault: true
    url: host.docker.internal:5431
    database: yourdb
    user: youruser
    password: yourpassword
    jsonData:
      sslmode: "disable"
   sslmode: "disable"
